optimizer_config:
  weight_decay: 0.01
  learning_rate: 0.00005
  min_lr: 6e-5
  max_lr: 6e-4
  warmup_steps: 0
  accumulation_steps: 10

training_config:
  max_steps: 20000
  batch_size: 4
  epochs: 10
  sequence_length: 1024
  log_path: logs
  step_log_training_loss: 10
  step_log_eval_loss: 500
  step_save_model: 500
  checkpoint_path: checkpoints
  report_to_wandb: true
  push_to_hub: true

ddp_config:
  master_process: true
  num_processes: 1
  process_rank: 0

device: cuda
